CREATE DATABASE DEPARTMENTS;
USE DEPARTMENTS;
CREATE TABLE Dept(DEPTNO INT PRIMARY KEY NOT NULL, DNAME VARCHAR(30) NOT NULL, LOC INT NOT NULL);
RENAME TABLE Dept TO department;
ALTER TABLE department ADD PINCODE INT NOT NULL;
ALTER TABLE department DROP PINCODE;
ALTER TABLE department CHANGE COLUMN DNAME DEPT_NAME VARCHAR(30) NOT NULL;
ALTER TABLE department MODIFY COLUMN LOC VARCHAR(10) NOT NULL;
DROP TABLE department;